on:
  push
jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install mise
        uses: jdx/mise-action@v2

      - name: Run stylua check
        run: mise run format -- --check
