on:
  push
jobs:
  stylua:
    runs-on: ubuntu-18.04
    container:
      image: sukovanej/stylua:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run stylua check
        shell: bash
        run: stylua --check .
